.github/workflows/demo.yml, .gitignore, Dockerfile, gulpfile.js, web/Pages/Data/File.cshtml.cs, web/atlas-demo-seed_script.sql, web/solr/bin/init.d/solr, web/solr/bin/install_solr_service.sh, web/solr/bin/oom_solr.sh, web/solr/bin/post, web/solr/bin/postlogs, web/solr/bin/solr, web/solr/bin/solr.cmd, web/solr/bin/solr.in.cmd, web/solr/bin/solr.in.sh, web/web.csproj, web/wwwroot/font/fontawesome/stylesheet.scss
=> bug fixes, demo

.github/workflows/demo.yml, Dockerfile, solr.Dockerfile
=> 2022.01.1 patch 1

Dockerfile
=> added analytics

Dockerfile
=> updated dotnet version in dockerfile

Dockerfile
=> fixed dll name

Dockerfile
=> added lookup connection

web/Pages/Collections/_Snippet.cshtml
=> fixed column name

.github/workflows/release.yaml, package.json
=> fix(fix release action): fix release action

.github/workflows/release.yaml
=> fix(release.yaml): fixed token

web/web.csproj
=> ci(sonar): updated sonar config

web/Pages/Terms/_Nav.cshtml
=> fix(term editor): term editor was not showing for unapproved terms

web/Pages/Profile/Index.cshtml.cs
=> feat(profile): added report last run date

solr.Dockerfile
=> build(solr docker): added install

solr.Dockerfile
=> moved settings files to .env

solr.Dockerfile
=> solr docker

web/Pages/Users/Index.cshtml
ETL now runs sql that is stored in the webapp. Cert tags can now be added in the settings. To Come:
allow editing cert tags from the report editor.
closes #186ETL now runs sql that is stored in the webapp. Cert tags can now be added in the settings. To Come:
allow editing cert tags from the report editor.
closes #186
=> feat(cert tags): moved cert tag logic into webapp

web/Authorization/ReportRunAuthorizationHandler.cs, web/Pages/Collections/Index.cshtml.cs, web/Pages/Reports/Index.cshtml.cs, web/Pages/Search/Index.cshtml.cs, web/Pages/Terms/Index.cshtml.cs, web/Pages/Users/Stars.cshtml.cs
=> chore(deps) Update all non-major dependencies

web/Migrations/20220725171135_ChangedOptionalIDsToRequiredUserFavoriteFolders.Designer.cs, web/Migrations/20220725174625_ChangedOptionalIDsToRequiredUserStars.Designer.cs, web/Migrations/20220725175645_ChangedOptionalIDsToRequiredRolePermissionLinks.Designer.cs, web/Migrations/20220725183921_ChangedOptionalIDsToRequiredReportObjectParameters.Designer.cs, web/Migrations/20220725184528_ChangedOptionalIDsToRequiredManageEngineTicket.Designer.cs, web/Migrations/20220725185112_ChangedOptionalIDsToRequiredMaintenanceLog.Designer.cs, web/Migrations/20220725191359_ChangedOptionalIDsToRequiredCollectionLinks.Designer.cs, web/Migrations/20220725194106_ChangedOptionalIDsToRequiredAnalytics.Designer.cs, web/Migrations/20220725205926_DatabaseColumnNameUpdate.Designer.cs, web/Migrations/20220726135356_ChangedOptionalIDsToRequiredReportObjectQuery.Designer.cs, web/Migrations/20220726163041_AddGroupPermissionSecurityPoint.Designer.cs, web/Migrations/20220726190357_AddGroupRoleLinksModel.Designer.cs, web/Migrations/20220726195839_CleanUpPermissions.Designer.cs, web/Migrations/20220802174122_AddETLEditPermission.Designer.cs, web/Migrations/Atlas_WebContextModelSnapshot.cs, web/Pages/Collections/Index.cshtml.cs, web/Pages/Collections/_All.cshtml, web/Pages/Terms/Index.cshtml.cs, web/wwwroot/js/essential.js
=> fix(migrations): fixed index name in migration builds

.github/workflows/test.yaml, package.json
=> chore(scripts): uPdated npm scripts

Dockerfile
=> chore(demo): updated demo settings

readme.md
=> chore(deps) Update dependency SixLabors.ImageSharp to v3

package.json, web/Pages/Users/Stars.cshtml
This fixes the create and rename folder bug. Moved the code to the end of the Stars.cshtml script.
the script feature and insertHTML was not working. Removed the script and moved the code to the end. This fixes the issues with favorites folders
fix #475
=> fix(stars.cshtml): Fix the create favorite folder
